spring.application.name=WordPocket

#Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5433/vocabularyDB
spring.datasource.username=vocabularyUSER
spring.datasource.password=vocabularyPASSWORD
#flyway
#spring.flyway.enabled=false